name: Idea
description: Far-future idea or concept not yet ready for planning
labels: ["idea"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is the idea? 1-3 sentences.
      placeholder: Simulate execution of ST code in a virtual runtime for testing logic without a physical PLC.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this be valuable?
      placeholder: Eliminates need for physical PLC during development. Faster feedback loop for logic testing.
    validations:
      required: true
