name: Technical Debt
description: Cleanup, refactoring, dependency updates, dead code removal
labels: ["technical-debt"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why does this need doing? What triggered it?
      placeholder: Dead code audit after parser rewrite (#41) found significant unused code.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Specific items to address. Be exhaustive.
      placeholder: |
        - src/parser.ts: pre-LSP parser, superseded by ast-parser.ts
        - src/shared/types.ts: STSymbolWithMembers (line 174) unused
        - 23 dead imports across 5 files
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance
      description: How do we know this is done?
      placeholder: |
        - All listed items removed or justified
        - Tests pass
        - Build succeeds
    validations:
      required: true
